language: python

# Python versions to test
python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage

# command to run tests
script:
#  - python -m unittest discover -s "testing"
  - coverage run --source cookiecutter setup.py test

after_success:
  - coveralls

# Os's to test on
os:
  - linux